# Göç, Sıcaklık, Yağış ve Aşırı Hava Olayları Verilerinin Temizlenmesi

Bu notebook, projede kullanılan ham veri setlerinin temizlenme sürecini içerir. Önce kapsam dışında kalan bölgesel göç verileri, ardından projede kullanılan veri setleri (Doğu-Güney Afrika, Batı-Orta Afrika göç verileri, sıcaklık, yağış ve afet verisi) sırasıyla işlenmiştir.

In [232]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (10, 5)

---
## Kullanılmayan bölgesel göç verileri

Proje kapsamı Doğu-Güney Afrika ve Batı-Orta Afrika ile sınırlı tutulduğu için aşağıdaki 4 bölge temizlendi ama son analize dahil edilmedi.

## Asya ve Pasifik

In [233]:
df_asya = pd.read_csv("/content/asya_ve_pasifik_goc_2000-2025.csv")
print(df_asya.shape)
df_asya.info()
df_asya.head()

(22399, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22399 entries, 0 to 22398
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   22399 non-null  int64
 1   Country of Asylum      22399 non-null  object
 2   Country of Origin      22399 non-null  object
 3   Country of Asylum ISO  22399 non-null  object
 4   Country of Origin ISO  22399 non-null  object
 5   Female 0 - 4           22399 non-null  int64
 6   Female 5 - 11          22399 non-null  int64
 7   Female 12 - 17         22399 non-null  int64
 8   Female 18 - 59         22399 non-null  int64
 9   Female 60+             22399 non-null  int64
 10  Female Other           22399 non-null  int64
 11  Female Total           22399 non-null  int64
 12  Male 0 - 4             22399 non-null  int64
 13  Male 5 - 11            22399 non-null  int64
 14  Male 12 - 17           22399 non-null  int64
 15  Male 18 - 59           22399 non-null  int64
 16  Male 60+               22399 non-null  int64
 17  Male Other             22399 non-null  int64
 18  Male Total             22399 non-null  int64
 19  Total                  22399 non-null  int64
dtypes: int64(16), object(4)
memory usage: 3.4+ MB

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,Afghanistan,Afghanistan,AFG,AFG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1200000
1,2001,Egypt,Afghanistan,EGY,AFG,5,0,0,9,0,5,19,0,0,9,43,0,16,68,87
2,2001,Australia,Afghanistan,AUS,AFG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6714
3,2001,Austria,Afghanistan,AUT,AFG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1049
4,2001,Azerbaijan,Afghanistan,AZE,AFG,44,88,75,121,6,0,334,56,105,89,578,12,0,840,1174

In [234]:
df_asya.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,22399.000000,22399.000000,22399.000000,22399.000000,2.239900e+04,22399.000000,22399.000000,2.239900e+04,22399.000000,22399.000000,22399.000000,22399.000000,22399.000000,22399.000000,2.239900e+04,2.239900e+04
mean,2014.249386,406.951114,613.777490,462.769365,1.367823e+03,138.447297,425.140140,3.414908e+03,420.211572,642.079870,492.419662,1512.048975,154.372517,494.035359,3.715168e+03,9.818025e+03
std,7.113676,8524.879174,12006.021795,8935.791368,2.408165e+04,3240.444559,11993.587146,5.729514e+04,8628.930964,12228.184754,8901.246778,23722.553046,2978.148436,12779.762967,5.754624e+04,1.222001e+05
min,2001.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,5.000000e+00
25%,2008.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,9.000000e+00
50%,2015.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,3.400000e+01
75%,2020.000000,0.000000,0.000000,0.000000,5.000000e+00,0.000000,0.000000,1.000000e+01,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000,1.700000e+01,2.410000e+02
max,2025.000000,424080.000000,689845.000000,471265.000000,1.063253e+06,268535.000000,909387.000000,2.617566e+06,420062.000000,656828.000000,373267.000000,913609.000000,181445.000000,985170.000000,2.222700e+06,4.840266e+06

In [235]:
# eksik değer ve duplicate kontrolü
print(df_asya.isnull().sum().sum(), "eksik hücre")
print(df_asya.duplicated(subset=["Year","Country of Asylum","Country of Origin"]).sum(), "duplicate satır")

0 eksik hücre
0 duplicate satır

Female/Male kırılım sütunlarının toplamı bazı satırlarda genel `Total` ile uyuşmuyor - UNHCR bazı yıllarda sadece toplam rakamı paylaşmış, kırılımı paylaşmamış. Bu yüzden kırılım sütunlarını kullanmayacağız, sadece `Total`'e güveneceğiz.

In [236]:
tutarsiz = df_asya[df_asya["Female Total"] + df_asya["Male Total"] != df_asya["Total"]]
print(len(tutarsiz), "satırda kırılım toplamı Total ile uyuşmuyor")

13656 satırda kırılım toplamı Total ile uyuşmuyor

`Total` sütununda IQR ile aykırı değer kontrolü - bunlar genelde gerçek kriz/savaş olayları olduğu için silinmiyor, sadece not ediliyor.

In [237]:
Q1, Q3 = df_asya["Total"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 1.5*IQR
print(((df_asya["Total"] > ust).sum()), "satır aykırı değer sınırının üstünde")
df_asya.nlargest(5, "Total")[["Year","Country of Asylum","Country of Origin","Total"]]

3926 satır aykırı değer sınırının üstünde

      Year Country of Asylum Country of Origin    Total
1769  2023       Afghanistan       Afghanistan  4840266
1988  2025       Afghanistan       Afghanistan  4231242
1666  2022       Afghanistan       Afghanistan  4221356
1565  2021       Afghanistan       Afghanistan  4035196
1877  2024       Afghanistan       Afghanistan  3872596

In [238]:
sutunlar_atilacak = [
    "Female 0 - 4", "Female 5 - 11", "Female 12 - 17", "Female 18 - 59", "Female 60+", "Female Other", "Female Total",
    "Male 0 - 4", "Male 5 - 11", "Male 12 - 17", "Male 18 - 59", "Male 60+", "Male Other", "Male Total"
]
df_asya_temiz = df_asya.drop(columns=sutunlar_atilacak)
df_asya_temiz.to_csv("goc_asya_pasifik_temiz.csv", index=False)
df_asya_temiz.shape

(22399, 6)

## Amerika Kıtası

In [239]:
df_amerika = pd.read_csv("/content/amerika_kitasi_goc_2000-2025.csv")
print(df_amerika.shape)
df_amerika.info()
df_amerika.head()

(12075, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12075 entries, 0 to 12074
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   12075 non-null  int64
 1   Country of Asylum      12075 non-null  object
 2   Country of Origin      12075 non-null  object
 3   Country of Asylum ISO  12075 non-null  object
 4   Country of Origin ISO  12075 non-null  object
 5   Female 0 - 4           12075 non-null  int64
 6   Female 5 - 11          12075 non-null  int64
 7   Female 12 - 17         12075 non-null  int64
 8   Female 18 - 59         12075 non-null  int64
 9   Female 60+             12075 non-null  int64
 10  Female Other           12075 non-null  int64
 11  Female Total           12075 non-null  int64
 12  Male 0 - 4             12075 non-null  int64
 13  Male 5 - 11            12075 non-null  int64
 14  Male 12 - 17           12075 non-null  int64
 15  Male 18 - 59           12075 non-null  int64
 16  Male 60+               12075 non-null  int64
 17  Male Other             12075 non-null  int64
 18  Male Total             12075 non-null  int64
 19  Total                  12075 non-null  int64
dtypes: int64(16), object(4)
memory usage: 1.8+ MB

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,Canada,Antigua and Barbuda,CAN,ATG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11
1,2002,Canada,Antigua and Barbuda,CAN,ATG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,41
2,2002,United States of America,Antigua and Barbuda,USA,ATG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
3,2003,Canada,Antigua and Barbuda,CAN,ATG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27
4,2004,Canada,Antigua and Barbuda,CAN,ATG,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20

In [240]:
df_amerika.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,12075.000000,12075.000000,12075.000000,12075.000000,1.207500e+04,12075.000000,1.207500e+04,1.207500e+04,12075.000000,12075.000000,12075.000000,1.207500e+04,12075.000000,1.207500e+04,1.207500e+04,1.207500e+04
mean,2015.716439,226.935238,419.650518,498.509979,2.571634e+03,341.895155,3.138028e+03,7.196653e+03,217.679172,415.806128,484.066749,2.413062e+03,307.152629,3.028122e+03,6.865889e+03,1.890307e+04
std,6.998302,6444.865524,9844.898202,11976.735257,5.808553e+04,11297.118440,9.061325e+04,1.324937e+05,5878.276903,9592.119656,11528.833308,5.358988e+04,10426.318753,8.695058e+04,1.252604e+05,2.832925e+05
min,2001.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
25%,2010.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,7.000000e+00
50%,2017.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,2.600000e+01
75%,2022.000000,0.000000,0.000000,0.000000,5.000000e+00,0.000000,0.000000e+00,1.200000e+01,0.000000,0.000000,0.000000,6.000000e+00,0.000000,0.000000e+00,1.500000e+01,1.885000e+02
max,2025.000000,577219.000000,623330.000000,635479.000000,2.620353e+06,769138.000000,4.307158e+06,4.533769e+06,524619.000000,579796.000000,577761.000000,2.320742e+06,677450.000000,4.069254e+06,4.219019e+06,9.494677e+06

In [241]:
# eksik değer ve duplicate kontrolü
print(df_amerika.isnull().sum().sum(), "eksik hücre")
print(df_amerika.duplicated(subset=["Year","Country of Asylum","Country of Origin"]).sum(), "duplicate satır")

0 eksik hücre
0 duplicate satır

Female/Male kırılım sütunlarının toplamı bazı satırlarda genel `Total` ile uyuşmuyor - UNHCR bazı yıllarda sadece toplam rakamı paylaşmış, kırılımı paylaşmamış. Bu yüzden kırılım sütunlarını kullanmayacağız, sadece `Total`'e güveneceğiz.

In [242]:
tutarsiz = df_amerika[df_amerika["Female Total"] + df_amerika["Male Total"] != df_amerika["Total"]]
print(len(tutarsiz), "satırda kırılım toplamı Total ile uyuşmuyor")

7515 satırda kırılım toplamı Total ile uyuşmuyor

`Total` sütununda IQR ile aykırı değer kontrolü - bunlar genelde gerçek kriz/savaş olayları olduğu için silinmiyor, sadece not ediliyor.

In [243]:
Q1, Q3 = df_amerika["Total"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 1.5*IQR
print(((df_amerika["Total"] > ust).sum()), "satır aykırı değer sınırının üstünde")
df_amerika.nlargest(5, "Total")[["Year","Country of Asylum","Country of Origin","Total"]]

2062 satır aykırı değer sınırının üstünde

      Year Country of Asylum Country of Origin    Total
2810  2020          Colombia          Colombia  9494677
2899  2022          Colombia          Colombia  8452850
2764  2019          Colombia          Colombia  8376412
2944  2023          Colombia          Colombia  8319673
3047  2025          Colombia          Colombia  8281874

In [244]:
sutunlar_atilacak = [
    "Female 0 - 4", "Female 5 - 11", "Female 12 - 17", "Female 18 - 59", "Female 60+", "Female Other", "Female Total",
    "Male 0 - 4", "Male 5 - 11", "Male 12 - 17", "Male 18 - 59", "Male 60+", "Male Other", "Male Total"
]
df_amerika_temiz = df_amerika.drop(columns=sutunlar_atilacak)
df_amerika_temiz.to_csv("goc_amerika_temiz.csv", index=False)
df_amerika_temiz.shape

(12075, 6)

## Avrupa

In [245]:
df_avrupa = pd.read_csv("/content/avrupa_goc_2000-2025.csv")
print(df_avrupa.shape)
df_avrupa.info()
df_avrupa.head()

(17635, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17635 entries, 0 to 17634
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   17635 non-null  int64
 1   Country of Asylum      17635 non-null  object
 2   Country of Origin      17635 non-null  object
 3   Country of Asylum ISO  17635 non-null  object
 4   Country of Origin ISO  17635 non-null  object
 5   Female 0 - 4           17635 non-null  int64
 6   Female 5 - 11          17635 non-null  int64
 7   Female 12 - 17         17635 non-null  int64
 8   Female 18 - 59         17635 non-null  int64
 9   Female 60+             17635 non-null  int64
 10  Female Other           17635 non-null  int64
 11  Female Total           17635 non-null  int64
 12  Male 0 - 4             17635 non-null  int64
 13  Male 5 - 11            17635 non-null  int64
 14  Male 12 - 17           17635 non-null  int64
 15  Male 18 - 59           17635 non-null  int64
 16  Male 60+               17635 non-null  int64
 17  Male Other             17635 non-null  int64
 18  Male Total             17635 non-null  int64
 19  Total                  17635 non-null  int64
dtypes: int64(16), object(4)
memory usage: 2.7+ MB

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,Egypt,Albania,EGY,ALB,0,5,0,0,0,0,5,0,0,0,0,0,0,0,5
1,2001,Argentina,Albania,ARG,ALB,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27
2,2001,Australia,Albania,AUS,ALB,0,0,0,0,0,0,0,0,0,0,0,0,0,0,129
3,2001,Austria,Albania,AUT,ALB,0,0,0,0,0,0,0,0,0,0,0,0,0,0,134
4,2001,Belgium,Albania,BEL,ALB,0,0,0,0,0,76,76,0,0,0,0,0,99,99,175

In [246]:
df_avrupa.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,17635.000000,17635.000000,17635.000000,17635.000000,1.763500e+04,17635.000000,1.763500e+04,1.763500e+04,17635.000000,17635.000000,17635.000000,1.763500e+04,17635.000000,1.763500e+04,1.763500e+04,1.763500e+04
mean,2013.716019,68.903601,130.245081,133.614063,8.215326e+02,267.315906,8.512228e+02,2.272834e+03,63.467083,133.084094,141.275758,6.661914e+02,170.201077,6.571849e+02,1.831404e+03,6.635448e+03
std,7.364241,2093.099813,3273.728714,3691.116145,2.252931e+04,8666.486615,2.187973e+04,4.577255e+04,1752.216922,3241.942754,3832.809297,1.586870e+04,5437.282127,1.662686e+04,3.427093e+04,9.580212e+04
min,2001.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
25%,2007.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,8.000000e+00
50%,2014.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,3.300000e+01
75%,2020.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,8.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,1.100000e+01,2.200000e+02
max,2025.000000,192000.000000,305000.000000,312000.000000,1.861000e+06,707000.000000,1.351840e+06,3.377000e+06,165000.000000,262000.000000,270000.000000,1.333000e+06,507000.000000,1.062160e+06,2.537000e+06,6.411343e+06

In [247]:
# eksik değer ve duplicate kontrolü
print(df_avrupa.isnull().sum().sum(), "eksik hücre")
print(df_avrupa.duplicated(subset=["Year","Country of Asylum","Country of Origin"]).sum(), "duplicate satır")

0 eksik hücre
0 duplicate satır

Female/Male kırılım sütunlarının toplamı bazı satırlarda genel `Total` ile uyuşmuyor - UNHCR bazı yıllarda sadece toplam rakamı paylaşmış, kırılımı paylaşmamış. Bu yüzden kırılım sütunlarını kullanmayacağız, sadece `Total`'e güveneceğiz.

In [248]:
tutarsiz = df_avrupa[df_avrupa["Female Total"] + df_avrupa["Male Total"] != df_avrupa["Total"]]
print(len(tutarsiz), "satırda kırılım toplamı Total ile uyuşmuyor")

11983 satırda kırılım toplamı Total ile uyuşmuyor

`Total` sütununda IQR ile aykırı değer kontrolü - bunlar genelde gerçek kriz/savaş olayları olduğu için silinmiyor, sadece not ediliyor.

In [249]:
Q1, Q3 = df_avrupa["Total"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 1.5*IQR
print(((df_avrupa["Total"] > ust).sum()), "satır aykırı değer sınırının üstünde")
df_avrupa.nlargest(5, "Total")[["Year","Country of Asylum","Country of Origin","Total"]]

3030 satır aykırı değer sınırının üstünde

       Year Country of Asylum Country of Origin    Total
17384  2022           Ukraine           Ukraine  6411343
17464  2023           Ukraine           Ukraine  4647361
17546  2024           Ukraine           Ukraine  4516644
17625  2025           Ukraine           Ukraine  4352380
17186  2019           Ukraine           Ukraine  2414000

In [250]:
sutunlar_atilacak = [
    "Female 0 - 4", "Female 5 - 11", "Female 12 - 17", "Female 18 - 59", "Female 60+", "Female Other", "Female Total",
    "Male 0 - 4", "Male 5 - 11", "Male 12 - 17", "Male 18 - 59", "Male 60+", "Male Other", "Male Total"
]
df_avrupa_temiz = df_avrupa.drop(columns=sutunlar_atilacak)
df_avrupa_temiz.to_csv("goc_avrupa_temiz.csv", index=False)
df_avrupa_temiz.shape

(17635, 6)

## Ortadoğu ve Kuzey Afrika

In [251]:
df_ortadogu = pd.read_csv("/content/ortadogu_ve_kuzey_afr._goc_2000-2025.csv")
print(df_ortadogu.shape)
df_ortadogu.info()
df_ortadogu.head()

(17603, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17603 entries, 0 to 17602
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   17603 non-null  int64
 1   Country of Asylum      17603 non-null  object
 2   Country of Origin      17603 non-null  object
 3   Country of Asylum ISO  17603 non-null  object
 4   Country of Origin ISO  17603 non-null  object
 5   Female 0 - 4           17603 non-null  int64
 6   Female 5 - 11          17603 non-null  int64
 7   Female 12 - 17         17603 non-null  int64
 8   Female 18 - 59         17603 non-null  int64
 9   Female 60+             17603 non-null  int64
 10  Female Other           17603 non-null  int64
 11  Female Total           17603 non-null  int64
 12  Male 0 - 4             17603 non-null  int64
 13  Male 5 - 11            17603 non-null  int64
 14  Male 12 - 17           17603 non-null  int64
 15  Male 18 - 59           17603 non-null  int64
 16  Male 60+               17603 non-null  int64
 17  Male Other             17603 non-null  int64
 18  Male Total             17603 non-null  int64
 19  Total                  17603 non-null  int64
dtypes: int64(16), object(4)
memory usage: 2.7+ MB

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,Egypt,Algeria,EGY,DZA,0,0,0,0,0,0,0,0,0,0,5,0,0,5,5
1,2001,Argentina,Algeria,ARG,DZA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,61
2,2001,Australia,Algeria,AUS,DZA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,357
3,2001,Austria,Algeria,AUT,DZA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6
4,2001,Belgium,Algeria,BEL,DZA,0,0,0,0,0,63,63,0,0,0,0,0,103,103,166

In [252]:
df_ortadogu.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,17603.000000,17603.000000,17603.000000,17603.000000,17603.000000,17603.000000,1.760300e+04,1.760300e+04,17603.000000,17603.000000,17603.00000,1.760300e+04,17603.000000,1.760300e+04,1.760300e+04,1.760300e+04
mean,2014.932625,395.822189,600.525649,435.209283,1448.281884,126.950917,4.553977e+02,3.462188e+03,406.160030,621.764472,475.89070,1.659639e+03,114.182696,5.018428e+02,3.779480e+03,1.959582e+04
std,6.974584,7414.252396,10552.395443,8004.094655,24178.615744,2027.876641,2.722318e+04,5.830317e+04,7546.743709,11004.866666,8509.96973,2.666657e+04,1881.057227,2.802311e+04,6.133799e+04,4.034704e+05
min,2001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
25%,2009.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,9.000000e+00
50%,2016.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000e+00,0.000000,0.000000e+00,5.000000e+00,3.100000e+01
75%,2021.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000e+00,1.300000e+01,0.000000,0.000000,0.00000,1.100000e+01,0.000000,0.000000e+00,2.600000e+01,2.400000e+02
max,2025.000000,343100.000000,400203.000000,428874.000000,943524.000000,85776.000000,2.231635e+06,2.231635e+06,343100.000000,440221.000000,428874.00000,1.075220e+06,85776.000000,2.295234e+06,2.295234e+06,2.388005e+07

In [253]:
# eksik değer ve duplicate kontrolü
print(df_ortadogu.isnull().sum().sum(), "eksik hücre")
print(df_ortadogu.duplicated(subset=["Year","Country of Asylum","Country of Origin"]).sum(), "duplicate satır")

0 eksik hücre
0 duplicate satır

Female/Male kırılım sütunlarının toplamı bazı satırlarda genel `Total` ile uyuşmuyor - UNHCR bazı yıllarda sadece toplam rakamı paylaşmış, kırılımı paylaşmamış. Bu yüzden kırılım sütunlarını kullanmayacağız, sadece `Total`'e güveneceğiz.

In [254]:
tutarsiz = df_ortadogu[df_ortadogu["Female Total"] + df_ortadogu["Male Total"] != df_ortadogu["Total"]]
print(len(tutarsiz), "satırda kırılım toplamı Total ile uyuşmuyor")

9308 satırda kırılım toplamı Total ile uyuşmuyor

`Total` sütununda IQR ile aykırı değer kontrolü - bunlar genelde gerçek kriz/savaş olayları olduğu için silinmiyor, sadece not ediliyor.

In [255]:
Q1, Q3 = df_ortadogu["Total"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 1.5*IQR
print(((df_ortadogu["Total"] > ust).sum()), "satır aykırı değer sınırının üstünde")
df_ortadogu.nlargest(5, "Total")[["Year","Country of Asylum","Country of Origin","Total"]]

3013 satır aykırı değer sınırının üstünde

       Year Country of Asylum Country of Origin     Total
14861  2024  Syrian Arab Rep.  Syrian Arab Rep.  23880052
14736  2023  Syrian Arab Rep.  Syrian Arab Rep.  23289649
14987  2025  Syrian Arab Rep.  Syrian Arab Rep.  22047185
14615  2022  Syrian Arab Rep.  Syrian Arab Rep.  21990714
13668  2014  Syrian Arab Rep.  Syrian Arab Rep.   7632500

In [256]:
sutunlar_atilacak = [
    "Female 0 - 4", "Female 5 - 11", "Female 12 - 17", "Female 18 - 59", "Female 60+", "Female Other", "Female Total",
    "Male 0 - 4", "Male 5 - 11", "Male 12 - 17", "Male 18 - 59", "Male 60+", "Male Other", "Male Total"
]
df_ortadogu_temiz = df_ortadogu.drop(columns=sutunlar_atilacak)
df_ortadogu_temiz.to_csv("goc_ortadogu_kuzeyafrika_temiz.csv", index=False)
df_ortadogu_temiz.shape

(17603, 6)

---
## Projede kullanılan veriler

Aşağıdaki 2 bölge (göç), sıcaklık, yağış ve afet verileri son analiz dosyasında birleştirildi.

## Doğu ve Güney Afrika

In [257]:
df_dogu_guney = pd.read_csv("/content/dogu_ve_guney_afrika_goc_verisi_2000-2025.csv")
print(df_dogu_guney.shape)
df_dogu_guney.info()
df_dogu_guney.head()

(19991, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19991 entries, 0 to 19990
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   19991 non-null  int64
 1   Country of Asylum      19991 non-null  object
 2   Country of Origin      19991 non-null  object
 3   Country of Asylum ISO  19991 non-null  object
 4   Country of Origin ISO  19991 non-null  object
 5   Female 0 - 4           19991 non-null  int64
 6   Female 5 - 11          19991 non-null  int64
 7   Female 12 - 17         19991 non-null  int64
 8   Female 18 - 59         19991 non-null  int64
 9   Female 60+             19991 non-null  int64
 10  Female Other           19991 non-null  int64
 11  Female Total           19991 non-null  int64
 12  Male 0 - 4             19991 non-null  int64
 13  Male 5 - 11            19991 non-null  int64
 14  Male 12 - 17           19991 non-null  int64
 15  Male 18 - 59           19991 non-null  int64
 16  Male 60+               19991 non-null  int64
 17  Male Other             19991 non-null  int64
 18  Male Total             19991 non-null  int64
 19  Total                  19991 non-null  int64
dtypes: int64(16), object(4)
memory usage: 3.1+ MB

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,Angola,Angola,AGO,AGO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,202000
1,2001,Argentina,Angola,ARG,AGO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16
2,2001,Australia,Angola,AUS,AGO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19
3,2001,Austria,Angola,AUT,AGO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23
4,2001,Belgium,Angola,BEL,AGO,0,0,0,0,0,140,140,0,0,0,0,0,169,169,309

In [258]:
df_dogu_guney.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,19991.000000,19991.000000,1.999100e+04,19991.000000,1.999100e+04,19991.000000,1.999100e+04,1.999100e+04,19991.000000,1.999100e+04,19991.000000,1.999100e+04,19991.000000,1.999100e+04,1.999100e+04,1.999100e+04
mean,2014.255065,648.736181,9.085590e+02,621.036266,1.773765e+03,169.486969,1.127863e+03,5.249446e+03,663.320894,9.596619e+02,661.850833,1.695383e+03,162.195138,1.125373e+03,5.267785e+03,1.476550e+04
std,7.111533,12133.352041,1.768733e+04,11726.516257,3.200412e+04,4054.410463,3.295661e+04,8.323996e+04,12513.300287,1.904721e+04,12502.918446,2.906522e+04,4132.937934,3.176139e+04,8.248671e+04,1.885069e+05
min,2001.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
25%,2008.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,9.000000e+00
50%,2015.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,5.000000e+00,3.500000e+01
75%,2020.000000,0.000000,0.000000e+00,0.000000,1.000000e+01,0.000000,0.000000e+00,2.300000e+01,0.000000,0.000000e+00,0.000000,1.700000e+01,0.000000,0.000000e+00,3.700000e+01,3.320000e+02
max,2025.000000,725061.000000,1.415500e+06,922354.000000,2.591373e+06,334102.000000,1.443552e+06,5.988390e+06,739606.000000,1.431469e+06,935189.000000,2.190040e+06,308099.000000,1.303106e+06,5.604403e+06,1.159279e+07

In [259]:
# eksik değer ve duplicate kontrolü
print(df_dogu_guney.isnull().sum().sum(), "eksik hücre")
print(df_dogu_guney.duplicated(subset=["Year","Country of Asylum","Country of Origin"]).sum(), "duplicate satır")

0 eksik hücre
0 duplicate satır

Female/Male kırılım sütunlarının toplamı bazı satırlarda genel `Total` ile uyuşmuyor - UNHCR bazı yıllarda sadece toplam rakamı paylaşmış, kırılımı paylaşmamış. Bu yüzden kırılım sütunlarını kullanmayacağız, sadece `Total`'e güveneceğiz.

In [260]:
tutarsiz = df_dogu_guney[df_dogu_guney["Female Total"] + df_dogu_guney["Male Total"] != df_dogu_guney["Total"]]
print(len(tutarsiz), "satırda kırılım toplamı Total ile uyuşmuyor")

9592 satırda kırılım toplamı Total ile uyuşmuyor

`Total` sütununda IQR ile aykırı değer kontrolü - bunlar genelde gerçek kriz/savaş olayları olduğu için silinmiyor, sadece not ediliyor.

In [261]:
Q1, Q3 = df_dogu_guney["Total"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 1.5*IQR
print(((df_dogu_guney["Total"] > ust).sum()), "satır aykırı değer sınırının üstünde")
df_dogu_guney.nlargest(5, "Total")[["Year","Country of Asylum","Country of Origin","Total"]]

3755 satır aykırı değer sınırının üstünde

       Year Country of Asylum Country of Origin     Total
16087  2024             Sudan             Sudan  11592793
16198  2025             Sudan             Sudan   9230596
15980  2023             Sudan             Sudan   9074483
7081   2024          Ethiopia          Ethiopia   4150050
13823  2024           Somalia           Somalia   3861856

En yüksek Total değerleri Sudan'ın 2023-2025 iç savaşına ait - gerçek veri, dokunulmuyor.

In [262]:
sutunlar_atilacak = [
    "Female 0 - 4", "Female 5 - 11", "Female 12 - 17", "Female 18 - 59", "Female 60+", "Female Other", "Female Total",
    "Male 0 - 4", "Male 5 - 11", "Male 12 - 17", "Male 18 - 59", "Male 60+", "Male Other", "Male Total"
]
df_dogu_guney_temiz = df_dogu_guney.drop(columns=sutunlar_atilacak)
df_dogu_guney_temiz.to_csv("goc_dogu_guney_afrika_temiz.csv", index=False)
df_dogu_guney_temiz.shape

(19991, 6)

## Batı ve Orta Afrika

In [263]:
df_bati_orta = pd.read_csv("/content/bati_ve_orta_afr._goc_2000-2025.csv")
print(df_bati_orta.shape)
df_bati_orta.info()
df_bati_orta.head()

(23564, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23564 entries, 0 to 23563
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   23564 non-null  int64
 1   Country of Asylum      23564 non-null  object
 2   Country of Origin      23564 non-null  object
 3   Country of Asylum ISO  23564 non-null  object
 4   Country of Origin ISO  23564 non-null  object
 5   Female 0 - 4           23564 non-null  int64
 6   Female 5 - 11          23564 non-null  int64
 7   Female 12 - 17         23564 non-null  int64
 8   Female 18 - 59         23564 non-null  int64
 9   Female 60+             23564 non-null  int64
 10  Female Other           23564 non-null  int64
 11  Female Total           23564 non-null  int64
 12  Male 0 - 4             23564 non-null  int64
 13  Male 5 - 11            23564 non-null  int64
 14  Male 12 - 17           23564 non-null  int64
 15  Male 18 - 59           23564 non-null  int64
 16  Male 60+               23564 non-null  int64
 17  Male Other             23564 non-null  int64
 18  Male Total             23564 non-null  int64
 19  Total                  23564 non-null  int64
dtypes: int64(16), object(4)
memory usage: 3.6+ MB

,Year,Country of Asylum,Country of Origin,Country of Asylum ISO,Country of Origin ISO,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
0,2001,Argentina,Benin,ARG,BEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6
1,2001,Burkina Faso,Benin,BFA,BEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
2,2001,Canada,Benin,CAN,BEN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23
3,2001,France,Benin,FRA,BEN,0,0,0,0,0,0,0,0,0,0,0,0,7,7,7
4,2001,Gabon,Benin,GAB,BEN,0,0,0,0,0,0,0,0,0,0,5,0,0,5,5

In [264]:
df_bati_orta.describe()

,Year,Female 0 - 4,Female 5 - 11,Female 12 - 17,Female 18 - 59,Female 60+,Female Other,Female Total,Male 0 - 4,Male 5 - 11,Male 12 - 17,Male 18 - 59,Male 60+,Male Other,Male Total,Total
count,23564.000000,23564.000000,23564.000000,23564.000000,23564.000000,23564.000000,2.356400e+04,2.356400e+04,23564.000000,23564.000000,23564.000000,23564.000000,23564.000000,2.356400e+04,2.356400e+04,2.356400e+04
mean,2014.209769,267.740324,411.181506,250.692073,726.335766,55.764811,4.503488e+02,2.162063e+03,266.091750,393.670896,251.376040,621.794008,47.192794,4.140902e+02,1.994216e+03,8.235283e+03
std,7.060389,7016.249159,9558.606216,5386.124889,14430.164178,1438.885915,1.777118e+04,4.123366e+04,6879.607091,8764.303067,5519.183984,11341.728259,1126.059051,1.536381e+04,3.632822e+04,1.376729e+05
min,2001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,5.000000e+00
25%,2008.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,9.000000e+00
50%,2015.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,5.000000e+00,2.900000e+01
75%,2020.000000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000e+00,1.600000e+01,0.000000,0.000000,0.000000,17.000000,0.000000,0.000000e+00,3.400000e+01,2.000000e+02
max,2025.000000,508704.000000,686795.000000,388093.000000,961191.000000,133844.000000,1.802324e+06,2.605579e+06,492716.000000,693286.000000,402053.000000,786223.000000,104244.000000,1.484557e+06,2.408674e+06,6.905511e+06

In [265]:
# eksik değer ve duplicate kontrolü
print(df_bati_orta.isnull().sum().sum(), "eksik hücre")
print(df_bati_orta.duplicated(subset=["Year","Country of Asylum","Country of Origin"]).sum(), "duplicate satır")

0 eksik hücre
0 duplicate satır

Female/Male kırılım sütunlarının toplamı bazı satırlarda genel `Total` ile uyuşmuyor - UNHCR bazı yıllarda sadece toplam rakamı paylaşmış, kırılımı paylaşmamış. Bu yüzden kırılım sütunlarını kullanmayacağız, sadece `Total`'e güveneceğiz.

In [266]:
tutarsiz = df_bati_orta[df_bati_orta["Female Total"] + df_bati_orta["Male Total"] != df_bati_orta["Total"]]
print(len(tutarsiz), "satırda kırılım toplamı Total ile uyuşmuyor")

11240 satırda kırılım toplamı Total ile uyuşmuyor

`Total` sütununda IQR ile aykırı değer kontrolü - bunlar genelde gerçek kriz/savaş olayları olduğu için silinmiyor, sadece not ediliyor.

In [267]:
Q1, Q3 = df_bati_orta["Total"].quantile([0.25, 0.75])
IQR = Q3 - Q1
ust = Q3 + 1.5*IQR
print(((df_bati_orta["Total"] > ust).sum()), "satır aykırı değer sınırının üstünde")
df_bati_orta.nlargest(5, "Total")[["Year","Country of Asylum","Country of Origin","Total"]]

3969 satır aykırı değer sınırının üstünde

      Year       Country of Asylum       Country of Origin    Total
8827  2024  Dem. Rep. of the Congo  Dem. Rep. of the Congo  6905511
8724  2023  Dem. Rep. of the Congo  Dem. Rep. of the Congo  6251790
8933  2025  Dem. Rep. of the Congo  Dem. Rep. of the Congo  5669479
8623  2022  Dem. Rep. of the Congo  Dem. Rep. of the Congo  5541021
8523  2021  Dem. Rep. of the Congo  Dem. Rep. of the Congo  5407840

En yüksek Total değerleri DR Kongo'nun iç göçüne ait - gerçek veri, dokunulmuyor.

In [268]:
sutunlar_atilacak = [
    "Female 0 - 4", "Female 5 - 11", "Female 12 - 17", "Female 18 - 59", "Female 60+", "Female Other", "Female Total",
    "Male 0 - 4", "Male 5 - 11", "Male 12 - 17", "Male 18 - 59", "Male 60+", "Male Other", "Male Total"
]
df_bati_orta_temiz = df_bati_orta.drop(columns=sutunlar_atilacak)
df_bati_orta_temiz.to_csv("goc_bati_orta_afrika_temiz.csv", index=False)
df_bati_orta_temiz.shape

(23564, 6)

---
## Sıcaklık

Bu veri diğerlerinden farklı - her satır bir ülke, her sütun bir yıl (wide format). Göç verileriyle birleştirebilmek için long formata çevireceğiz.

In [269]:
sicaklik = pd.read_excel("/content/yıllık ortalama sıcaklık.xlsx", sheet_name="all")
print(sicaklik.shape)
sicaklik.head()

(246, 127)

,code,name,1901-07,1902-07,1903-07,1904-07,1905-07,1906-07,1907-07,1908-07,...,2016-07,2017-07,2018-07,2019-07,2020-07,2021-07,2022-07,2023-07,2024-07,2025-07
0,ABW,Aruba (Neth.),28.22,27.79,27.89,27.62,27.68,27.58,27.56,27.46,...,29.68,29.27,28.97,29.37,29.41,29.06,28.88,29.43,29.59,29.38
1,AFG,Afghanistan,12.77,12.99,11.82,12.14,12.05,12.51,11.89,12.20,...,14.31,13.90,14.18,13.82,13.19,14.35,14.47,14.62,14.26,14.76
2,AGO,Angola,21.32,21.36,21.37,21.28,21.32,21.20,21.22,21.29,...,21.94,21.82,21.66,21.81,21.73,21.73,21.62,21.56,21.70,21.52
3,AIA,Anguilla (U.K.),27.17,26.74,26.80,26.29,26.68,26.42,26.09,26.24,...,28.16,27.96,27.69,28.08,28.10,27.96,27.82,28.28,28.65,28.45
4,ALA,ALA,5.39,3.43,5.29,4.72,5.17,5.70,4.55,4.88,...,6.35,6.18,6.91,6.95,7.78,6.26,6.92,6.66,7.30,7.45

İki satır (Bouvet Island, Saint-Barthélemy) 125 yılın tamamında boş - bunları atıyoruz.

In [270]:
yil_sutunlari = [c for c in sicaklik.columns if c not in ["code","name"]]
bos_satirlar = sicaklik[sicaklik[yil_sutunlari].isna().all(axis=1)]
print(bos_satirlar[["code","name"]])

   code                    name
26  BLM  Saint-Barthélemy (Fr.)
35  BVT    Bouvet Island (Nor.)

In [271]:
sicaklik = sicaklik[~sicaklik["code"].isin(["BVT","BLM"])].reset_index(drop=True)

sicaklik_long = sicaklik.melt(id_vars=["code","name"], var_name="Year", value_name="Avg_Temp")
sicaklik_long["Year"] = sicaklik_long["Year"].str.split("-").str[0].astype(int)
sicaklik_long = sicaklik_long.rename(columns={"code":"Country ISO","name":"Country"})[["Year","Country","Country ISO","Avg_Temp"]]

print(sicaklik_long.shape)
print(sicaklik_long["Avg_Temp"].isna().sum(), "eksik değer")

(30500, 4)
1 eksik değer

Kalan tek eksik değer (Mongolia, 1925) - komşu yıllardan lineer enterpolasyonla dolduruyoruz.

In [272]:
sicaklik_long = sicaklik_long.sort_values(["Country ISO","Year"])
sicaklik_long["Avg_Temp"] = sicaklik_long.groupby("Country ISO")["Avg_Temp"].transform(lambda x: x.interpolate())
sicaklik_long = sicaklik_long.sort_values(["Year","Country ISO"]).reset_index(drop=True)

print(sicaklik_long["Avg_Temp"].isna().sum(), "eksik değer kaldı")
sicaklik_long.to_csv("yillik_ortalama_sicaklik_temiz.csv", index=False)

0 eksik değer kaldı

---
## Yağış

Sıcaklıkla aynı yapı, aynı işlemler.

In [273]:
yagis = pd.read_excel("/content/yıllık_ortalama_yagis.xlsx", sheet_name="all")
yagis = yagis[~yagis["code"].isin(["BVT","BLM"])].reset_index(drop=True)

yagis_long = yagis.melt(id_vars=["code","name"], var_name="Year", value_name="Avg_Precip")
yagis_long["Year"] = yagis_long["Year"].str.split("-").str[0].astype(int)
yagis_long = yagis_long.rename(columns={"code":"Country ISO","name":"Country"})[["Year","Country","Country ISO","Avg_Precip"]]
yagis_long = yagis_long.sort_values(["Year","Country ISO"]).reset_index(drop=True)

print(yagis_long.shape)
print(yagis_long["Avg_Precip"].isna().sum(), "eksik değer")
print((yagis_long["Avg_Precip"]<0).sum(), "negatif değer")

yagis_long.to_csv("yillik_ortalama_yagis_temiz.csv", index=False)

(30500, 4)
0 eksik değer
0 negatif değer

---
## Afet (kuraklık, sel, fırtına, aşırı sıcaklık)

Bu veri olay bazlı - her satır tek bir afet. Göç verisiyle aynı kapsama (2001-2025) çekip Yıl+Ülke bazında özetleyeceğiz.

In [274]:
afet = pd.read_excel("/content/temiz kuraklık, sel, sis, fırtına, aşırı sıcaklık verileri tüm dünya.xlsx")
print(afet.shape)
afet["Disaster Type"].value_counts()

(12906, 25)

Disaster Type
Flood                  6203
Storm                  5169
Drought                 804
Extreme temperature     730
Name: count, dtype: int64

Start Date, End Date'ten sonra olamaz. Bu koşulu sağlamayan satırlar var, kontrol edelim.

In [275]:
afet["sd"] = pd.to_datetime(afet["Start Date"])
afet["ed"] = pd.to_datetime(afet["End Date"])
ters = afet[afet["sd"] > afet["ed"]]
print(len(ters), "satırda Start Date > End Date")

188 satırda Start Date > End Date

Bir kayıtta (DisNo. 1988-0424-VEN) yıl alanı bozuk - DisNo olayın 1988'e ait olduğunu gösteriyor, Start Date'i End Date ile aynı yapıyoruz. Diğer 187 satır ise Start/End'in yer değiştirmesi - swap ettiğimizde süre 1-335 gün arası çıkıyor (mantıklı), bu yüzden swap ile düzeltiyoruz.

In [276]:
ven_mask = afet["DisNo."] == "1988-0424-VEN"
afet.loc[ven_mask, "Start Date"] = afet.loc[ven_mask, "End Date"]

afet["sd"] = pd.to_datetime(afet["Start Date"])
afet["ed"] = pd.to_datetime(afet["End Date"])
ters_mask = (afet["sd"] > afet["ed"]) & (~ven_mask)
afet.loc[ters_mask, ["Start Date","End Date"]] = afet.loc[ters_mask, ["End Date","Start Date"]].values

afet["sd"] = pd.to_datetime(afet["Start Date"])
afet["ed"] = pd.to_datetime(afet["End Date"])
print((afet["sd"] > afet["ed"]).sum(), "kalan ters tarih")

afet["Start_Year"] = afet["sd"].dt.year
afet = afet[(afet["Start_Year"]>=2001)&(afet["Start_Year"]<=2025)].drop(columns=["sd","ed"]).reset_index(drop=True)
print(afet.shape)

afet.to_csv("afet_verisi_temiz.csv", index=False)

0 kalan ters tarih
(7768, 26)

Bir ülke-yılda birden fazla afet olabildiği için (örn. bazı yıllarda 30+), göç verisiyle birleştirmeden önce Yıl+Ülke bazında özetliyoruz.

In [277]:
afet_ozet = afet.groupby(["Start_Year","ISO","Country"]).agg(
    Afet_Sayisi=("DisNo.","count"),
    Kuraklik_Sayisi=("Disaster Type", lambda x: (x=="Drought").sum()),
    Sel_Sayisi=("Disaster Type", lambda x: (x=="Flood").sum()),
    Firtina_Sayisi=("Disaster Type", lambda x: (x=="Storm").sum()),
    Asiri_Sicaklik_Sayisi=("Disaster Type", lambda x: (x=="Extreme temperature").sum()),
    Toplam_Olum=("Total Deaths","sum"),
    Toplam_Etkilenen=("Total Affected","sum"),
    Toplam_Hasar_1000USD=("Total Damage ('000 US$)","sum"),
).reset_index().rename(columns={"Start_Year":"Year"})

print(afet_ozet.shape)
print(afet_ozet["Afet_Sayisi"].sum() == len(afet))

afet_ozet.to_csv("afet_yil_ulke_ozet.csv", index=False)

(2825, 11)
True